---

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      #      image: freebsd-11-2-release-amd64

  env:
    matrix:
      - ansible_version: "2.5.15"
        python_version: "python3.6"
        python_pkg: "python36"
        jailName: "molecule"
        execPrefix: "cbsd jexec jname=molecule"
      - ansible_version: "2.6.14"
        python_version: "python3.6"
        python_pkg: "python36"
        jailName: "molecule"
        execPrefix: "cbsd jexec jname=molecule"
      - ansible_version: "2.7.8"
        python_version: "python3.6"
        python_pkg: "python36"
        jailName: "molecule"
        execPrefix: "cbsd jexec jname=molecule"

  prepare_script:
    - sed -i '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf
    - $CIRRUS_WORKING_DIR/molecule/cirrusci/scripts/configure_freebsd_ci_jail.sh $jailName $CIRRUS_WORKING_DIR;
    - $execPrefix sed -i -- '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf;
    - $execPrefix pkg update -f;
    - $execPrefix pkg install -y $python_pkg > /dev/null;
    - cbsd jstop jname=$jailName

  install_script:
    # install tooling on the host
    - pkg upgrade -y
    - pkg install -y $python_pkg git
    - alias python='/usr/local/bin/$python_version'
    - python -m ensurepip --default-pip
    - pip install --upgrade pip
    # Install Ansible
    - pip3 install ansible==$ansible_version
    # Install Molecule
    - pip3 install molecule
    # Check Python version
    - python3 --version
    # Check Ansible version
    - ansible --version
    # Check Molecule version
    - molecule --version

  script: |
    git clone https://github.com/network-shark/ansible-role-unbound.git
    ls -l
    pwd
    ls $CIRRUS_WORKING_DIR
    cd $CIRRUS_WORKING_DIR
    pwd
    #    molecule --debug test -s cirrusci
    cbsd jstart jname=$jailName
    molecule --debug lint -s cirrusci
    molecule --debug syntax -s cirrusci
    molecule --debug create -s cirrusci
    molecule --debug destroy -s cirrusci
    molecule --debug create -s cirrusci
    molecule --debug converge -s cirrusci
