---
env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64
  OS: FreeBSD
#  - ANSIBLE_VERSION=2.2
#  - ANSIBLE_VERSION=2.3
#  - ANSIBLE_VERSION=2.4
#  - ANSIBLE_VERSION=2.5
#  - ANSIBLE_VERSION=2.6
#  - ANSIBLE_VERSION=2.7

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      #      image: freebsd-11-2-release-amd64
  install_script:
    - pkg upgrade -y
    - pkg install python27 curl
    - alias python='/usr/local/bin/python2.7'
    - python get-pip.py
    # Install Ansible
    - pip install ansible
    # Install Molecule
    - pip install molecule
    # Check Python version
    - python27 --version
    # Check Ansible version
    - ansible --version

    # Check Molecule version
    - molecule --version


  script: |
    molecule --debug test -s vagrant
