---

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-0-release-amd64
      #      image: freebsd-11-2-release-amd64

  env:
    matrix:
      - ansible_version: "ansible2.4"
        python_version: "python3.6"
      - ansible_version: "ansible2.5"
        python_version: "python3.6"
      - ansible_version: "ansible2.6"
        python_version: "python3.6"
      - ansible_version: "ansible2.7"
        python_version: "python3.6"



  install_script:

    - pkg upgrade -y
    - pkg install -y $python_version
    - alias python='/usr/local/bin/$python_version'
    - python -m ensurepip --default-pip
    - pip install --upgrade pip
    # Install Ansible
    - pip3 install $ansible_version
    # Install Molecule
    - pip3 install molecule
    # Check Python version
    - python3 --version
    # Check Ansible version
    - ansible --version
    # Check Molecule version
    - molecule --version

    - echo $CIRRUS_WORKING_DIR

  script: |
    cd $CIRRUS_WORKING_DIR
    molecule --debug test -s cirrusci
