---
- name: Debug unbound-checkconf
  command: whereis unbound-checkconf
  register: test
  changed_when: false

- name: Show whereis
  debug:
    msg: "{{ test }}"

- name: Debug Cirrus CI
  command: "{{ item }}"
  loop:
    - whoami
    - ls /usr/local/sbin/
    - env
    - whereis unbound-checkconf
  register: debug_env
  changed_when: false

- name: Show Cirrus CI Env
  debug:
    msg: "{{ debug_env }}"
# vim: set ts=2 sw=2:
