---

- include: dist_vars.yml

- include: install.yml

- include: debug.yml

- name: Configure unbound.conf
  template:
    src: unbound.conf.j2
    dest: "{{ unbound_conf_path }}"
  notify: restart unbound

- name: Check if unbound_server.key is present
  stat:
    path: "{{ unbound_directory }}/unbound_server.key"
  register: unbound_remote_keys
- name: Setup certificates
  command: unbound-control-setup
  when: |
    unbound_control_enable == "yes" and not unbound_remote_keys.stat.exists

- include: root_anchor.yml
  when: unbound_auto_trust_anchor_file|default(false)

# Cannot move this part as the `verify` component of the previous task, because
# unbound-checkconf fails if the file is outside {{ unbound_directory }}
- name: Check unbound.conf
  command: /usr/local/sbin/unbound-checkconf "{{ unbound_conf_path }}"
  changed_when: false
- name: Enable unbound service
  service:
    name: "{{ unbound_service_name }}"
    state: started
    enabled: true
  when: unbound_enable_service

# vim: set ts=2 sw=2:
