---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: moleculel

lint:
  name: yamllint
  truthy: disable
provisioner:
  name: ansible
  playbooks:
    create: create.yml
    converge: playbook.yml
    destroy: destroy.yml
  verbose: vvvvv
  log: true
  inventory:
    host_vars:
      freebsd_instance:
        ansible_connection: jail
    group_vars:
      all:
        ansible_python_interpreter: "/usr/local/bin/python2.7"
  lint:
    name: ansible-lint
scenario:
  name: cirrusci
verifier:
  name: testinfra
  lint:
    name: flake8
