---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: freebsd_instance

lint:
  name: yamllint
  truthy: disable
provisioner:
  name: ansible
  verbose: vvv
  log: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: "/usr/local/bin/python3.6"
  lint:
    name: ansible-lint
scenario:
  name: cirrusci
verifier:
  name: testinfra
  lint:
    name: flake8
